### ISSUE TITLE
Git.Tutorial seems outdated

### ISSUE THREAD

**Issue by yaccz** [jwiegley/gitlib#52] opened 2015-07-09 22:11 UTC
Since

```
commit 5353208ba83917a2293a4ff897d4885d3badc00b
CommitDate: Mon Jan 28 01:31:40 2013 -0600
```

at least.

```
~/gitlib.git git:5353208... 
yac@beefcake % grr 'resolveRef ::' -A 1
gitlib/Git.hs:55:    resolveRef :: Text -> m Oid
gitlib/Git.hs-56-    resolveRef name = lookupRef name >>= \ref ->
--------------------------------------------------------------------------------
~/gitlib.git git:5353208... 
yac@beefcake % g co 5353208^                                                                                                            
Previous HEAD position was 5353208... Libgit2 Blob reading/writing works with new API
HEAD is now at c915222... Further Git.hs updates
--------------------------------------------------------------------------------
~/gitlib.git git:c915222... 
yac@beefcake % grr 'resolveRef ::' -A 1
gitlib/Data/Git/Reference.hs:110:resolveRef :: Repository -> Text -> IO (Maybe Oid)
gitlib/Data/Git/Reference.hs-111-resolveRef repos name = alloca $ \ptr -> do
--
gitlib/Git.hs:53:    resolveRef :: Text -> m Oid
gitlib/Git.hs-54-    resolveRef name = lookupRef name >>= \ref ->
```

**Comment by jwiegley** [comment] 2015-07-09 22:49
It's sorely out of date.

I've completed a rewrite of the core gitlib, to become 4.0, for which a new tutorial will be written before release.

**Comment by jwiegley** [comment] 2015-07-09 22:49
It's on the `v4` branch.

**Comment by thejohnfreeman** [comment] 2015-08-16 01:13
When might v4 be due? Is there a tutorial or some docs for the existing v3.1? Thanks!

**Comment by jwiegley** [comment] 2015-08-16 04:16
I won't be writing a tutorial for 3.x, but I intend to for 4, since the structure is becoming quite nice now.

If you want to beta test v4, let me know.

**Comment by thejohnfreeman** [comment] 2015-08-16 20:28
I'll use System.Process and just wait for the release. I'm still new to Haskell, so I won't be able to tell the difference between a bug and my own misunderstanding.

**Comment by hjwylde** [comment] 2015-11-09 10:35
+1

Found this repo and am interested in using it, but I find it quite difficult to use. I look forward to an up-to-date tutorial!

**Comment by jwiegley** [comment] 2017-02-16 06:22
Duplicate of #38

**Closed by jwiegley** 2017-02-16 06:22 UTC
